// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HeaderController from "./header_controller"
import ErrorController from "./error_controller"
import SidebarController from "./sidebar_controller"
import ModalController from "./modal_controller"
import HostController from "./host_controller"

application.register("header", HeaderController)
application.register("error", ErrorController)
application.register("sidebar", SidebarController)
application.register("modal", ModalController)
application.register("host", HostController)
