import './packages/jquery.js'
import './packages/jquery-ui.js'
import './packages/select2.js'
import '@activeadmin/activeadmin/app/assets/javascripts/active_admin/base.js'
import 'activeadmin_addons/src/all.js'
